spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  h2:
    console:
      enabled: false
  cache:
    type: simple
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    com.sisinnov.pms: INFO
    org.springframework: WARN
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health