global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'project-management-system'

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'project-management-system'
          environment: 'development'